name: zymmo
description: "Plataforma gastronômica colaborativa e social."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Atualizado para SDK mais recente

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.1 # Dart 3: ^3.0.0
  firebase_auth: ^5.1.1 # Dart 3: ^5.0.0
  cloud_firestore: ^5.0.2 # Dart 3: ^5.0.0
  firebase_storage: ^12.1.0 # Dart 3: ^12.0.0

  # State Management (Provider)
  provider: ^6.0.5

  # Google Fonts for Unna and Open Sans
  google_fonts: ^6.1.0

  # For generating unique IDs
  uuid: ^4.2.1

  # For picking images
  image_picker: ^1.0.4

  # Icons
  cupertino_icons: ^1.0.6
  # Você pode adicionar outros pacotes de ícones se necessário, ex: font_awesome_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # Dart 3: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/ # Adicione seus logos aqui
    - assets/icons/ # Adicione seus ícones aqui
    - assets/images/ # Para imagens de placeholder ou onboarding, se houver

  # An example of declaring fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  # fonts:
  #   - family: Unna
  #     fonts:
  #       - asset: fonts/Unna-Regular.ttf
  #       - asset: fonts/Unna-Bold.ttf
  #         weight: 700
  #   - family: OpenSans
  #     fonts:
  #       - asset: fonts/OpenSans-Regular.ttf
  #       - asset: fonts/OpenSans-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/OpenSans-Bold.ttf
  #         weight: 700
  # (Nota: google_fonts é usado, então a declaração manual acima é um exemplo,
  # mas não é estritamente necessária se as fontes estiverem no Google Fonts)
